name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6        
        with:          
          node-version: lts/*
      - name: Install dependencies        
        run: npm install
      - name: Install ci dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Check style        
        run: npm run lint
      - name: Run test        
        run: npm run test
      - name: Build app
        run: npm run build
      - name: Start app
        run: npm run start-prod &
      - name: Run e2e Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Trigger deployment
        # if: ${{ (contains((github.event.commits.*.message), '#skip')) }}
        if: ${{ (github.event_name == 'push') && (contains(join(github.event.commits.*.message), '#skip') == false) }}
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
        - uses: sarisia/actions-status-discord@v1
      - name: Notify Discord
        if: ${{ success() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: "Hey <@316911818725392384>"
          title: "deploy"
          description: "Build and deploy to GitHub Pages"
          color: 0x0000ff
          url: "https://github.com/sarisia/actions-status-discord"
          username: GitHub Actions
          avatar_url: ${{ secrets.AVATAR_URL }}

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ (contains(join(github.event.commits.*.message), '#skip') == false) }}
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch